//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Website.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        public int ProductCode { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductImage { get; set; }
    }
}
